name: checkout
run-name: Checkout

on:
  - push

jobs:
  checkout-and-list-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -la
      - name: Checkout
        run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}"
            git fetch origin
            git checkout main

      - name: list files after
        run: ls -la