name: ci
run-name: CI

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./tw-todos/

jobs:
  runt-test-and-build:
    uses: ./.github/workflows/test-and-build.yaml
    secrets: inherit
